### ISSUE TITLE
iOS 13 not work

### ISSUE THREAD

**Issue by moxcomic** [Building42/Telegraph#79] opened 2020-02-26 08:50 UTC
[SERVER] Server is running - url: https://localhost:9000
[CLIENT] WebSocket connected - host: localhost
[SERVER] WebSocket connected - name: Yvo
[SERVER] WebSocket message sent: <WebSocketMessage: opcode: textFrame, payload: 'Welcome client Yvo'>
[CLIENT] WebSocket message received - text: Welcome client Yvo
[SERVER] WebSocket message sent: <WebSocketMessage: opcode: binaryFrame, payload: 6 bytes>
[CLIENT] WebSocket message received - data: {length = 6, bytes = 0x000102030405}
2020-02-26 16:49:55.975332+0800 iOS Example[51320:2164973] Task <438B7EBE-FA4D-412E-9613-EAF317D8CACE>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://localhost:9000/hello, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://localhost:9000/hello}
[CLIENT] Request failed - status: 0 - error: cancelled
2020-02-26 16:49:55.978356+0800 iOS Example[51320:2164969] Task <B2EE2B69-C235-4FBB-BE97-85498A959B6E>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://localhost:9000/data, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://localhost:9000/data}
[CLIENT] Request failed - status: 0 - error: cancelled
2020-02-26 16:49:55.983168+0800 iOS Example[51320:2164968] Task <438B7EBE-FA4D-412E-9613-EAF317D8CACE>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
2020-02-26 16:49:55.983883+0800 iOS Example[51320:2164968] Connection 2: unable to determine interface type without an established connection
2020-02-26 16:49:55.984106+0800 iOS Example[51320:2164968] Connection 2: unable to determine fallback status without a connection
2020-02-26 16:49:55.988112+0800 iOS Example[51320:2164968] Task <B2EE2B69-C235-4FBB-BE97-85498A959B6E>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
[SERVER] WebSocket message sent: <WebSocketMessage: opcode: ping, payload: none>
[SERVER] WebSocket message received: <WebSocketMessage: opcode: pong, payload: none>
[SERVER] WebSocket message sent: <WebSocketMessage: opcode: ping, payload: none>
[SERVER] WebSocket message received: <WebSocketMessage: opcode: pong, payload: none>

**Comment by yvbeek** [comment] 2020-03-02 02:44
Duplicate of https://github.com/Building42/Telegraph/issues/71

**Closed by yvbeek** 2020-03-02 02:44 UTC
