### ISSUE TITLE
Swift Compiler Warning (Xcode 13) - Using Class is deprecated use AnyObject instead

### ISSUE THREAD

**Issue by Mondingnibai** [Building42/Telegraph#121] opened 2022-02-07 08:00 UTC
I just updated my Xcode  version to 13 because Im preparing the app  to upgrade for iOS 15. But I got these errors. 
Do I need to fix manually? Or I will wait for your next update.
If I fix it manually, what would be the cause or errors might happen?
<img width="596" alt="Screen Shot 2022-02-07 at 3 59 54 PM" src="https://user-images.githubusercontent.com/78613015/152747908-432911ec-aec4-4d4c-8a55-50e3db091a22.png">

**Comment by yvbeek** [comment] 2022-08-12 21:07
Hi, these warnings were caused by some outdated Swift code. This has been resolved by this PR: https://github.com/Building42/Telegraph/pull/130

**Closed by yvbeek** 2022-08-12 21:07 UTC
